name: 'Build iso'

on: [push]

jobs:
  main:
    name: 'iso builder'
    runs-on: archlinux-latest

    env:
      BUILD_CONTAINER: ${{ matrix.compiler }}-build-container

    steps:
      - run: docker run --priviledge --name $BUILD_CONTAINER

