name: 'Build iso'
description: 'A github action to build the iso'

on: [push]

jobs:
  main:
    name: 'iso builder'
    using: 'docker'
    image: 'Dockerfile'
    env:
      BUILD_CONTAINER: ${{ matrix.compiler }}-build-container
    steps:
      run: |
        docker run --priviledge --name $BUILD_CONTAINER

